export const WEEKDAY_IDS = [
  "montag",
  "dienstag",
  "mittwoch",
  "donnerstag",
  "freitag",
  "samstag",
  "sonntag",
] as const;

export type WeekdayId = (typeof WEEKDAY_IDS)[number];

export type StoryBlock =
  | { type: "text"; text: string }
  | { type: "sceneBreak" };

export interface StoryChapter {
  id: WeekdayId;
  weekday: string;
  title: string;
  blocks: StoryBlock[];
}

export const STORY_TITLE = "Eine verhexte Woche";
export const STORY_SUBTITLE = "Das Tagebuch der Hexe Anabella Declutter";

export const storyChapters: StoryChapter[] = [
  {
    id: "montag",
    weekday: "Montag",
    title: "Der Tag, an dem die Zeit verschwand und sich alles vor mir versteckte",
    blocks: [
      { type: "text", text: "Der Wecker brauchte nur einen kurzen Piep von sich zu geben und schon tasteten meine Finger den \"Aus\"-Knopf und drückten ihn. Mein Kissen war weich, meine Decke warm, mein Kuscheltier ganz fest in meinen Armen und meine Augen waren schneller wieder zu, als ich bis drei zählen konnte." },
      { type: "text", text: "Ein Kitzeln auf meiner Nase weckte mich. Ich öffnete meine Augen und sah, wie ein weicher Schwanz vor meinem Gesicht wedelte." },
      { type: "text", text: "\"Krümel!\", rief ich, und mein orangener Kater schreckte auf und ließ ein ungeduldiges Miauen von sich. \"Warum ist Krümel jetzt schon hier?\"" },
      { type: "text", text: "\"Weil du ein kleines Schlafmützchen bist, Anabella\", meine Mama stand vor meinem Bett und machte die Gardinen vor meinem Fenster auf. Die Sonne schien in das Zimmer wie ein Scheinwerferlicht und ich musste meine Augen zusammenkneifen. \"Es ist schon sieben Uhr dreißig, du kommst noch zu spät zur Schule!\"" },
      { type: "text", text: "Was? Sieben Uhr dreißig? Ich schüttelte die Decke von mir und zack, war ich auf den Beinen. Das kann doch nicht sein! Ich kann doch nicht eine halbe Stunde verschlafen haben!" },
      { type: "text", text: "\"Oh, ich bin so doof, ich habe heute Morgen meinen Wecker einfach ausgemacht …\", murmelte ich. Das ist mir schon so oft passiert und jedes Mal nehme ich mir vor, das nicht mehr zu tun." },
      { type: "text", text: "\"Du bist doch nicht doof, mein Schatz\", sagte meine Mama und gab mir einen Kuss auf die Stirn. \"Ich bleibe auch manchmal gerne länger im Bett liegen. Jedem geht es mal so. Beeil dich jetzt einfach ein bisschen.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Ich zog mich an und packte meine Sachen so schnell ich konnte. Schulbücher, Federtasche, Zauberbuch und … Zauberstab? Oh nein, wo hatte ich denn meinen Zauberstab schon wieder liegen gelassen? Ich suchte auf meinem Bett, unter meinem Bett, auf meinem Schreibtisch, in meinem Schrank, nichts!" },
      { type: "text", text: "\"Papa?\", fragte ich, als ich in die Küche kam. \"Hast du vielleicht meinen Zauberstab gesehen?\"" },
      { type: "text", text: "\"Hast du den schon wieder verlegt, Anabella?\", er schaute mich mit hochgezogener Augenbraue an." },
      { type: "text", text: "\"Nein, nein!\", sagte ich. \"Der … ähh… Der versteckt sich nur vor mir.\"" },
      { type: "text", text: "\"Genau, natürlich!\", lachte mein Papa. \"Ich helfe dir beim Suchen.\"" },
      { type: "text", text: "Auch er schaute in jedem Raum, in jeder Ecke, in allen Taschen, der Zauberstab war nirgends zu finden." },
      { type: "text", text: "\"Dann musst du heute ohne Zauberstab in die Schule, Schatz\", sagte mein Vater schulterzuckend." },
      { type: "text", text: "\"Na gut …\" Ich war niedergeschlagen. Wir sollten heute einen neuen Zauberspruch lernen und ohne meinen Zauberstab würde ich da nicht mitmachen können. \"Dann fliege ich jetzt los …\"" },
      { type: "sceneBreak" },
      { type: "text", text: "\"Hast du denn schon deine Zähne geputzt?\", rief Mama. Ich seufzte. Hört denn dieser Morgen niemals auf? Ich ging ins Bad und wollte gerade Zahnpasta auf meine Bürste schmieren, als Krümel mit meinem Zauberstab im Mund durch die Tür spaziert kam. Er legte mir den Stab vor die Füße und machte \"miau\", als wolle er mir sagen: \"Hier, bitte, da hast du ihn\"." },
      { type: "text", text: "\"Krümel, ich danke dir!\", rief ich vor Freude. \"Wo hast du den denn gefunden?\"" },
      { type: "text", text: "Wieder machte Krümel nur \"miau\"." },
      { type: "text", text: "\"Er war in seinem Katzenfutter\", sagte Mama und lachte. \"Ich weiß echt nicht, wie du das immer machst, Anabella.\"" },
      { type: "text", text: "\"Ich auch nicht, Mama\", sagte ich. \"Aber ich bin erleichtert, dass er wieder da ist.\"" },
      { type: "text", text: "Ich packte ihn schnell in meinen Rucksack, zog meine Schuhe an und wollte mich sofort wieder auf meinen Besen schwingen, als meine Mutter mir wieder die Zahnbürste vor die Nase hielt." },
      { type: "text", text: "\"Ja, ja, ich putz mir ja schon die Zähne\", grummelte ich augenrollend und zog die Schuhe wieder aus." },
      { type: "sceneBreak" },
      { type: "text", text: "Während ich mit der Bürste die Zahnpasta in meinem Mund verteilte und sich der Pfefferminzgeschmack breit machte, dachte ich darüber nach, wie sich der Morgen unendlich anfühlte. Das Verschlafen, das Anziehen, das Packen meiner Sachen, die Suche nach meinem Stab, das hat doch alles so lange gedauert. Ich schaute auf die Uhr im Bad und erwartete, viel zu spät dran zu sein, sah aber, dass seit heute Morgen nur zwanzig Minuten vergangen waren. Ich hatte noch zehn Minuten, bevor ich losgehen müsste. Sofort beruhigte sich meine Stimmung. Perfekt! Ich kann noch pünktlich sein!" },
      { type: "text", text: "Als ich mir die Zähne zu Ende geputzt hatte und angefangen hatte, meine Schuhe wieder anzuziehen, schlängelte sich Krümel um meine Beine herum. Ich beugte mich runter zu ihm und streichelte sein weiches Fell." },
      { type: "text", text: "\"Du hast mich heute gerettet!\", flüsterte ich ihm zu. \"Danke, dass du meinen Zauberstab gefunden hast.\" Krümel rieb als Antwort seinen Kopf gegen mein Knie. Er war so warm und schnurrte, wenn man ihm über die Stirn strich. Seine Augen waren giftgrün, und wenn er spielen wollte, dann wurden sie manchmal ganz schwarz. Ich konnte sehen, dass er in Spiellaune war. Noch ein bisschen hatte ich ja Zeit, also holte ich Krümels Lieblingsspielzeug und ein paar Leckerlis und belohnte Krümel für den Fund meines Zauberstabs." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Anabella!\", rief meine Mutter. \"Du bist noch immer nicht los?\"" },
      { type: "text", text: "\"Hä\", machte ich. \"Aber Mama, ich hab doch noch ein bisschen Zeit.\"" },
      { type: "text", text: "\"Nein, Schatz\", schüttelte Mama den Kopf. \"Es ist schon fünf nach acht, du bist spät dran.\"" },
      { type: "text", text: "Ich warf alles hin und rannte zu meinem Besen. Wenn ich schnell flog, dann schaffte ich es vielleicht noch." },
      { type: "text", text: "Ich war etwas enttäuscht von mir, aber allzu überrascht war ich nicht. So oft komme ich zu spät, obwohl ich mir Mühe gebe, es nicht zu tun. Ich fragte mich, wie alle anderen immer pünktlich waren und warum ich nicht so war wie alle anderen." },
      { type: "sceneBreak" },
      { type: "text", text: "Als ich von der Schule wieder nach Hause kam, warteten meine Eltern mit einem Päckchen, Papier und vielen bunten Stiften auf mich." },
      { type: "text", text: "\"Anabella, wir haben nachgedacht\", fing mein Papa an. Meine Mama nickte. \"Wir wissen, wie schwierig es für dich ist, morgens loszukommen.\"" },
      { type: "text", text: "Ich ließ meinen Blick sinken. Mich störte, dass es mir so schwerfiel, wenn es für andere Kinder viel leichter schien." },
      { type: "text", text: "\"Es hat mit deiner ADHS zu tun\", sagte mein Papa. \"Jedes Gehirn funktioniert ein bisschen anders, und mit ADHS ist es manchmal schwierig für das Gehirn, den Überblick zu behalten.\"" },
      { type: "text", text: "\"Deshalb haben wir uns was für dich ausgedacht\", sagte meine Mama und hielt die Box hoch. \"Wenn dein Gehirn den Überblick nicht behalten kann, dann sorgen wir dafür, dass dein Umfeld den Überblick für dich behält.\"" },
      { type: "text", text: "\"Wie soll das denn gehen?\", fragte ich." },
      { type: "text", text: "Mein Papa nahm eine Armbanduhr aus dem Karton. \"Viele Menschen haben eine sogenannte innere Uhr - sie wissen ungefähr, wie viel Zeit vergeht. Für andere ist das aber nicht so klar.\"" },
      { type: "text", text: "\"Für mich ist das gar nicht klar\", nickte ich. \"Mal habe ich das Gefühl es vergehen Stunden, wenn es eigentlich nur Minuten waren und manchmal habe ich das Gefühl die Zeit verschwindet einfach, ohne dass ich etwas merke.\"" },
      { type: "text", text: "\"Genau deshalb brauchst du etwas von außen, das dir genau zeigt, wie viel Zeit vergeht\", sagte meine Mama, und mein Papa hielt mir die Armbanduhr hin. Sie war schön, verziert mit Kätzchen drauf, die so aussahen wie Krümel. \"Auf der Uhr kannst du die Zeit ablesen, aber auch Timer und Wecker stellen.\"" },
      { type: "text", text: "\"Das ist ja super\", sagte ich." },
      { type: "text", text: "\"Und das ist nicht alles!\", sagte mein Papa." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Für dein Zimmer haben wir einen neuen Wecker gekauft, einen, den du morgens nicht so leicht ausmachen kannst. Du musst nämlich erstmal eine Matheaufgabe lösen, erst dann geht er aus!\"" },
      { type: "text", text: "\"Und wenn ich die Aufgabe gelöst habe, dann bin ich schon richtig wach und gehe nicht wieder schlafen!\", sagte ich glücklich. Ich konnte es kaum erwarten, das morgen zu versuchen." },
      { type: "text", text: "\"Genau! Und ich habe ein kleines Regal neben deine Tür gebaut, wo alle deine Schulsachen reinpassen. Da ist sogar ein Ständer, extra für deinen Zauberstab, wie ein kleines Zuhause für ihn. Wenn du den Stab immer nach der Schule in sein Zuhause stellst, wirst du ihn nicht mehr verlieren.\"" },
      { type: "text", text: "\"Das probiere ich gleich!\", sagte ich. \"Und wozu sind die ganzen Stifte?\"" },
      { type: "text", text: "\"Damit du an das Zähneputzen denkst\", sagte Mama. \"Und an andere Sachen natürlich, alles, was morgens wichtig ist. Lass uns zusammen eine Morgen-Checkliste basteln, die du dann abhaken kannst. Da stehen dann Sachen drauf wie Anziehen, Zähne putzen, Frühstücken, …\"" },
      { type: "text", text: "\"Krümel streicheln!\", rief ich." },
      { type: "text", text: "\"Ja, wir können auch Krümel streicheln raufschreiben. Wollen wir die Liste zusammen machen?\"" },
      { type: "text", text: "\"Los geht's!\"" },
    ],
  },
  {
    id: "dienstag",
    weekday: "Dienstag",
    title: "Der Tag, an dem die Träumelise den Zappelphilipp kennenlernte",
    blocks: [
      { type: "text", text: "Heute war ich pünktlich in der Schule. Die Tricks von Mama und Papa hatten gut funktioniert! Die Matheaufgabe hat mein Gehirn richtig in Fahrt gebracht am Morgen, ich konnte gar nicht verschlafen. Ich hatte alles auf meiner Checkliste abgehakt, meinen Zauberstab von seinem Zuhause abgeholt und meine Armbanduhr umgemacht. Ich fühlte mich unbesiegbar. Meine Eltern hatten mir aber auch gesagt, dass ich nicht so böse zu mir selbst sein soll, wenn es mal doch nicht so gut klappt." },
      { type: "text", text: "In der ersten Stunde kam meine Lehrerin, Frau Tintenklecks, zusammen mit einem neuen Jungen in die Klasse. Sie stellte ihn als Finn Fidget vor, einen Jungen, der neu mit seiner Familie in die Stadt gezogen war." },
      { type: "text", text: "\"Seid nett zu ihm!\", hatte sie noch gesagt, und \"Setz dich doch zu Anabella an den Tisch.\"" },
      { type: "text", text: "Na toll. Ich hatte den Neuen an der Backe." },
      { type: "text", text: "In der zweiten Stunde kippelte Finn die ganze Zeit und ich hatte Schwierigkeiten im Unterricht zuzuhören." },
      { type: "text", text: "In der dritten Stunde fing er dann an, auf dem Tisch rumzutippeln, das machte mich verrückt." },
      { type: "text", text: "In der vierten Stunde zappelte er dann so doll herum, dass er versehentlich meine Wasserflasche vom Tisch warf." },
      { type: "text", text: "\"Finn\", zischte ich. \"Wieso kannst du denn nicht stillsitzen? Ich kann mich gar nicht konzentrieren!\"" },
      { type: "text", text: "\"Tut mir leid!\", flüsterte Finn und war den Rest der Stunde weitgehend ruhig. Ich konnte aber sehen, wie er mit den Beinen wackelte." },
      { type: "sceneBreak" },
      { type: "text", text: "In der Pause lief mir Finn hinterher. \"Anabella!\", rief er. \"Kann ich mal mit dir reden?\"" },
      { type: "text", text: "Ich rollte mit den Augen, blieb aber stehen." },
      { type: "text", text: "\"Ich wollte mich für vorhin entschuldigen. Ich habe gar nicht bemerkt, wie viel ich mich bewegt habe\", sagte er." },
      { type: "text", text: "Ich fühlte mich sofort ein bisschen schlecht dafür, dass ich so genervt reagiert habe. \"Du hast es nicht bemerkt?\", fragte ich." },
      { type: "text", text: "\"Nein, weißt du, ich habe ADHS und habe deswegen Schwierigkeiten richtig still zu sitzen.\"" },
      { type: "text", text: "\"Das kann gar nicht sein\", sagte ich bestimmt. \"Ich habe nämlich auch ADHS und ich kann sehr wohl still sitzen.\"" },
      { type: "text", text: "\"Dann hast du wahrscheinlich ADS!\", sagte Finn." },
      { type: "text", text: "Ich schüttelte den Kopf. Was weiß der denn schon?" },
      { type: "text", text: "\"Meine Mama hat mir das erklärt\", sagte er. \"Sie hat mir gesagt, dass es ADHS und ADS gibt. Und mit beidem kann man sich nicht so gut konzentrieren. Aber bei ADHS kann man zusätzlich auch nicht stillsitzen. Das H, hat sie gesagt, steht nämlich für Hüp… Hiperaktionität oder sowas.\"" },
      { type: "text", text: "\"Hyperaktivität\", sagte Frau Tintenklecks, die plötzlich hinter uns aufgetaucht war. \"Kommt mal mit, ihr beiden, dann kann ich euch ein bisschen was darüber erzählen.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Frau Tintenklecks setzte sich mit uns wieder in den Klassenraum. \"Ich hab gehört, wie ihr über verschiedene Arten von ADHS geredet habt. ADHS steht für Aufmerksamkeitsdefizit-/Hyperaktivitätsstörung. Das ist ein langes Wort, aber ich erkläre euch gleich, was es bedeutet\", sagte sie und schrieb Aufmerksamkeitsdefizit-/Hyperaktivitätsstörung ganz groß an die Tafel." },
      { type: "text", text: "\"Aufmerksamkeits-defizit\", las ich laut. \"Was ist denn ein Defizit?\"" },
      { type: "text", text: "\"Das ist eine sehr gute Frage, Anabella!\", lächelte Frau Tintenklecks. \"Ein Defizit bedeutet, dass es zu wenig von etwas gibt, in diesem Fall, zu wenig Aufmerksamkeit.\"" },
      { type: "text", text: "Ich schaute aus dem Fenster. Da kletterte gerade ein Eichhörnchen einen Baumstamm hoch. Zu wenig Aufmerksamkeit. Was heißt das denn überhaupt? Heißt das, dass ich mehr Aufmerksamkeit haben will? Oder vielleicht wollte Finn mehr Aufmerksamkeit, so wie er rumzappelte." },
      { type: "text", text: "So viel hatte er gezappelt, dass meine Wasserflasche vom Tisch gefallen ist. Das ist doch nicht normal. Da fällt mir ein, ich habe heute noch nichts getrunken. Mein Mund war ganz trocken. Und gegessen hatte ich auch noch nicht. Nicht so wie das Eichhörnchen draußen, das sich gerade eine Haselnuss aufknabberte." },
      { type: "text", text: "\"Anabella?\", fragte Frau Tintenklecks und ich schreckte hoch. \"Bist du ein bisschen abgedriftet?\"" },
      { type: "sceneBreak" },
      { type: "text", text: "\"Was soll das denn heißen?\", fragte ich ein wenig eingeschnappt." },
      { type: "text", text: "\"Das soll heißen, dass du angefangen hast, über andere Dinge nachzudenken, als mir zuzuhören. Oder?\"" },
      { type: "text", text: "\"Tut mir leid\", murmelte ich." },
      { type: "text", text: "\"Das ist gar kein Problem\", sagte Frau Tintenklecks. \"Aber genau das ist mit Aufmerksamkeitsdefizit gemeint. Du hast Schwierigkeiten, bei einer Sache zu bleiben.\"" },
      { type: "text", text: "\"Ich habe also zu wenig Aufmerksamkeit und kann mich deswegen nicht so gut auf eine Sache konzentrieren?\", fragte ich." },
      { type: "text", text: "\"Genau, das bedeutet Aufmerksamkeitsdefizit. Aber ich verrate auch mal etwas. Ganz so stimmt das nämlich nicht! Es ist eigentlich kein Aufmerksamkeitsdefizit, sondern ein Aufmerksamkeits-kontroll-problem. Gibt es nicht manchmal ein paar Dinge, auf die du dich super gut konzentrieren kannst, Anabella?\"" },
      { type: "text", text: "\"Ja!\", nickte ich. \"Auf den Zaubersprücheunterricht und wenn ich zeichne!\"" },
      { type: "text", text: "\"Wenn ich Fußballspiele und auf meinem Besen fliege!\", sagte Finn. \"Oder auch wenn ich Videospiele spiele, da meckern dann meine Eltern, dass ich zu lange vor der Konsole sitze.\"" },
      { type: "text", text: "\"Beim Basteln, beim Blumenpflücken, beim Zaubertränkebrauen\", erzählte ich weiter." },
      { type: "text", text: "\"Beim Musikmachen!\", rief Finn." },
      { type: "text", text: "\"Das ist ja toll!\", warf Frau Tintenklecks ein. \"Es gibt ganz viele Sachen, auf die ihr euch super konzentrieren könnt! Da habt ihr dann nicht zu wenig Aufmerksamkeit, sondern vielleicht sogar manchmal zu viel.\"" },
      { type: "text", text: "\"Aber ich dachte, es ist ein Defizit\", sagte ich verwirrt." },
      { type: "text", text: "\"Das dachte man ganz lange!\", sagte Frau Tintenklecks. \"Deswegen heißt es auch so. Aber eigentlich habt ihr genug Aufmerksamkeit. Nur worauf ihr sie richtet, ist nicht immer in eurer Kontrolle. Wenn ihr etwas ganz langweilig findet, dann sucht sich euer Gehirn spannendere Dinge zum Angucken, wie zum Beispiel das Eichhörnchen draußen. Und wenn ihr etwas ganz toll findet, dann ist es manchmal sogar schwer die Aufmerksamkeit davon wegzurichten, wie beim Videospiele spielen.\"" },
      { type: "text", text: "\"Das stimmt\", sagte Finn. \"Manchmal habe ich ganz viel Aufmerksamkeit und manchmal ganz wenig.\"" },
      { type: "text", text: "\"Manchmal möchte ich gerne zuhören, aber es fällt mir total schwer. Ich habe das Gefühl, das ist nicht in meiner Kontrolle.\", sagte ich." },
      { type: "text", text: "\"Und manchmal, da bin ich so versunken in eine Sache, da vergesse ich zu essen, zu trinken oder sogar aufs Klo zu gehen!\", sagte Finn." },
      { type: "text", text: "\"Ich auch!\", lachte ich. \"Das ist auch nicht immer in meiner Kontrolle.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "\"Kommen wir zum zweiten Teil: Die Hyperaktivitätsstörung\", sagte Frau Tintenklecks und zeigte wieder auf die Tafel." },
      { type: "text", text: "\"Nicht stillsitzen können!\", rief Finn." },
      { type: "text", text: "\"Ganz genau\", sagte sie. \"Wir können uns ADHS vorstellen, wie eine Uhr, die schneller sein möchte, als sie eigentlich ist. Das geht gar nicht. Also zappeln die Uhrzeiger herum.\"" },
      { type: "text", text: "\"Das verstehe ich nicht\", sagte Finn." },
      { type: "text", text: "\"Die Uhr kann gar nicht schneller werden. Sie muss warten, bis die Zeiger sich Sekunde um Sekunde bewegen. Warten ist aber ganz schwierig für ADHS-Gehirne. Deshalb füllen sie die Wartezeit mit Aktivität. Zappeln, Tippeln, auf den Nägeln kauen, kippeln, wackeln, manchmal auch aufstehen und herumlaufen.\"" },
      { type: "text", text: "\"Ich hasse warten\", sagte Finn." },
      { type: "text", text: "\"Ich auch\", murmelte ich. \"Aber ich zappel nicht so rum wie Finn.\"" },
      { type: "text", text: "\"Nein, Anabella, bei dir passiert das alles innerlich. Du hast ganz viele Gedanken, Träumereien und manchmal wirst du auch ganz müde, oder?\"" },
      { type: "text", text: "\"Ja, genau\", sagte ich. \"Finn bewegt sich also ganz viel, um das Warten auszuhalten, und ich träume stattdessen?\"" },
      { type: "text", text: "\"Ganz richtig erfasst\", nickte Frau Tintenklecks. \"ADHS kann bei jedem ganz anders aussehen, auch wenn der Kern der Gleiche ist.\"" },
      { type: "text", text: "\"Ist das dann ADS, so wie Finn es gesagt hat?\"" },
      { type: "text", text: "\"Das kann man so sagen, ist aber ein bisschen veraltet. Heutzutage weiß man nämlich, dass die Symptome von ADHS sich im Verlauf des Lebens verändern können. Das heißt, den Unterschied zwischen ADS und ADHS gibt es nicht wirklich so genau. Es kann sein, Anabella, dass du später doch ein bisschen unruhiger wirst und dafür vielleicht ein bisschen weniger träumst und Finn, dass du ein bisschen stiller sitzt.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "\"Also haben wir beide ADHS?\", fragte ich nochmal." },
      { type: "text", text: "\"Genau\", nickte Frau Tintenklecks. \"Und auch wenn ihr euch beide unterschiedlich verhaltet, ihr habt doch ganz viel gemeinsam. Hier, ich hab noch was für euch.\"" },
      { type: "text", text: "Sie drückte uns beiden einen kleinen Ball in die Hand, den man kneten und verformen konnte. \"Ihr könnt im Unterricht damit spielen, vielleicht hilft euch das weniger zu zappeln und zu träumen.\"" },
      { type: "text", text: "Wir bedankten uns bei Frau Tintenklecks für die Erklärung. Wir beide wussten nun mehr über uns und das fühlte sich gut an." },
      { type: "text", text: "\"Ich werde nicht mehr so genervt sein, wenn du dich viel bewegst, Finn, es tut mir leid, dass ich dich so angeschnauzt habe\", sagte ich." },
      { type: "text", text: "\"Entschuldigung angenommen!\", lächelte Finn. \"Und wenn du möchtest, kann ich dich hin und wieder mal anstupsen, wenn ich sehe, dass du verträumt aus dem Fenster schaust.\"" },
      { type: "text", text: "\"Gerne!\", sagte ich, und ich hatte das Gefühl, das war der Anfang einer tollen Freundschaft." },
    ],
  },
  {
    id: "mittwoch",
    weekday: "Mittwoch",
    title: "Der Tag, an dem das Zimmer unordentlicher wurde, je mehr ich aufräumte",
    blocks: [
      { type: "text", text: "Als ich heute wach wurde, brachte mich nicht nur meine Wecker-Mathe-Aufgabe ins Knobeln, sondern auch die Frage, wie mein Zimmer innerhalb kürzester Zeit in einen Saustall verwandelt werden konnte." },
      { type: "text", text: "Am Sonntag noch hatten Papa und ich gemeinsam aufgeräumt und jetzt liegen überall schon wieder Berge an Kleidung, Blätter, Zaubertrankzutaten und Spielzeug." },
      { type: "text", text: "Ich musste große Schritte über die Hindernisse machen, um aus meinem Zimmer zu kommen." },
      { type: "text", text: "In der Schule traf ich wieder Finn, wir beide hatten unseren Knetball dabei. Immer wenn wir damit spielten, lächelte Frau Tintenklecks uns an. Es hat wirklich geholfen, etwas in der Hand zu haben! Ich konnte ein wenig besser zuhören, und Finn hat meine Wasserflasche dieses Mal heil gelassen." },
      { type: "text", text: "Nach der Schule fragte mich Finn, ob wir nicht etwas zusammen unternehmen wollten, und ich sagte sofort ja, also flogen wir gemeinsam nach Hause. Was ich jedoch vergessen hatte, war der Zustand meines Zimmers." },
      { type: "text", text: "\"Oh nein, Anabella, dein Zimmer ist ja genau wie meins!\", lachte Finn." },
      { type: "text", text: "Ich schämte mich in Grund und Boden. Es war unbetretbar!" },
      { type: "text", text: "\"Es tut mir so leid, Finn, ich hätte aufräumen sollen, bevor ich dich zu mir einlade.\"" },
      { type: "text", text: "\"Ach was\", sagte Finn. \"Ich kenne das doch von mir selber. Außerdem verbringe ich lieber ein bisschen Zeit mit dir in einem unordentlichen Zimmer, als gar keine Zeit mit dir zu verbringen!\"" },
      { type: "text", text: "Als er das sagte, fühlte ich mich ein wenig besser." },
      { type: "text", text: "\"Ich kann dir auch beim Aufräumen helfen\", sagte Finn." },
      { type: "text", text: "\"Wirklich, das würdest du machen?\", fragte ich." },
      { type: "text", text: "\"Na klar, wozu sind denn Freunde da?\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Wir waren hochmotiviert, wussten aber nicht wirklich, wo wir anfangen sollten. Wir schoben die Sachen hin und her, hoben hier und da etwas auf und packten es weg, sortierten ein paar Blätter und Bücher, aber das Zimmer blieb so chaotisch wie davor. Wir wussten nicht, was wir falsch gemacht haben." },
      { type: "text", text: "\"Vielleicht fangen wir nochmal mit den Büchern an?\", fragte Finn." },
      { type: "text", text: "Gesagt, getan. Eines nach dem anderen nahmen wir in die Hand und stellten es ins Regal. Das große Sprüchebuch, die Zaubertrankbrauerin, Teil eins und Teil zwei, der Drache und der Esel, die Fee im Dunkelwald und … als wir das nächste Buch aufhoben, sprang Finn glücklich auf." },
      { type: "text", text: "\"Die Königin des Feuers! Das ist mein Lieblingsbuch!\", rief er." },
      { type: "text", text: "\"Wirklich? Meins auch!\"" },
      { type: "text", text: "Er zeigte mir sein Lieblingskapitel und erzählte davon, wie er sich vorstellte, eines Tages selber Feuerzauber zu lernen. Ich zeigte ihm meine Versuche, einen Feuertrank zu brauen." },
      { type: "text", text: "\"Hier, du nimmst eine Phönixfeder und eine Löwenzahnblüte, du mischst dann noch ein paar Katzenhaare rein - die habe ich von Krümel!\", erzählte ich. \"Ach, warte, du hast Krümel ja noch gar nicht kennengelernt!\"" },
      { type: "text", text: "Ich rannte aus dem Zimmer und kam mit einem protestierenden Krümel im Schlepptau zurück. \"Hier! Das ist mein magischer Kater.\"" },
      { type: "text", text: "\"Oh, was ist denn magisch an ihm?\"" },
      { type: "text", text: "\"Guck mal!\" Ich nahm einen Stift vom Boden und warf ihn ganz hoch in die Luft und schwupps, war Krümel schon am Fliegen. Er schnappte sich den Stift und schwebte vorsichtig wieder zurück zu uns." },
      { type: "text", text: "\"Wow, das möchte ich auch ausprobieren!\", sagte Finn begeistert und hob ebenfalls etwas vom Boden auf und warf es in die Luft." },
      { type: "text", text: "So ging es weiter, bis Mama nach Hause kam und ich ihr Finn vorstellte. Dann sah sie mein Zimmer." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Anabella, was ist denn hier passiert?\", fragte sie erschrocken. \"Dein Zimmer sieht ja zehnmal schlimmer aus als heute Morgen!\"" },
      { type: "text", text: "Finn und ich schauten uns enttäuscht an. \"Wir haben versucht aufzuräumen …\", sagte ich verlegen." },
      { type: "text", text: "\"Das hat ja gut funktioniert!\", sagte Mama sarkastisch." },
      { type: "text", text: "Auch Papa kam jetzt nach Hause." },
      { type: "text", text: "\"Au weia\", sagte er. Na toll, jetzt haben alle mein schreckliches Zimmer gesehen. Ich wollte vom Boden verschluckt werden." },
      { type: "text", text: "\"Ich bin stolz auf euch, dass ihr versucht habt, das Zimmer aufzuräumen!\", sagte Mama dann. \"Manchmal läuft es nicht so gut, das ist normal. Fangt doch erstmal mit etwas Kleinem an. Wie wär's, wenn ihr erstmal alle Stifte einsammelt und in deine Federtasche tut.\"" },
      { type: "text", text: "\"Und noch was\", sagte Papa. \"Machen wir doch einen kleinen Wettbewerb daraus. Wer von euch beiden schneller aufräumt, darf sich als Belohnung aussuchen, was ihr gemeinsam machen wollt.\"" },
      { type: "text", text: "Finn und mir brauchte man das nicht zweimal sagen. Sofort machten wir uns ans Werk und auf magische Weise klappte es dieses Mal ganz gut." },
      { type: "text", text: "Ich sammelte die Stifte auf, ich faltete meine Wäsche zusammen und hob meine Zaubertrankzutaten auf. Hier und da gab es ein paar Sachen, mit denen ich mich lieber ein bisschen länger beschäftigt hätte, zum Beispiel wollte ich Finn gerne meine neue Zeichnung zeigen oder die neue Armbanduhr, die meine Eltern mir gegeben hatten, aber ich wollte auch die Wette gewinnen. Also tat ich meine Gedanken beiseite und räumte weiter auf." },
      { type: "text", text: "Ich machte das Bett, räumte die Bücher weg und organisierte meinen Schreibtisch." },
      { type: "text", text: "\"Fertig!\", rief Finn dann plötzlich. \"Ich bin fertig mit meinen Aufgaben.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Ich hatte noch ein paar lose Zettel in der Hand, als er rief. Mist, er war wohl doch vor mir fertig geworden." },
      { type: "text", text: "\"Super gemacht, Finn!\", sagte Papa und ich war ein bisschen traurig. \"Anabella, du hast es auch toll gemacht! Du musst nur noch deine Zettel wegpacken, und schon ist dein Zimmer blitzblank.\"" },
      { type: "text", text: "Meine Niederlage tat nicht lange weh, denn Finn suchte sich eine tolle Belohnung aus: Die Sonne schien in das saubere Zimmer, Krümel schwebte im Raum herum und Papa, Mama, Finn und ich schauten glücklich zusammen einen Film." },
      { type: "text", text: "\"Nächstes Mal schlage ich dich aber\", flüsterte ich Finn zu." },
      { type: "text", text: "\"Na, das wollen wir mal sehen …\"" },
    ],
  },
  {
    id: "donnerstag",
    weekday: "Donnerstag",
    title: "Der Tag, an dem ich tausend andere Dinge machte (und nicht meine Hausaufgaben)",
    blocks: [
      { type: "text", text: "Ich wollte mir die Haare vom Kopf reißen. Ich hätte gerne meine Stifte kaputt gemacht, meine Blätter zerrissen und mit einem Hammer den Tisch geteilt. Und gerne hätte ich am Ende alles in Brand gesteckt." },
      { type: "text", text: "Ja, ich musste einen Aufsatz schreiben." },
      { type: "text", text: "Und Finn, der musste das auch. Und so, wie er gerade aussah und sich rumbewegte, hatte er wahrscheinlich die gleichen Gedanken wie ich." },
      { type: "text", text: "Okay. Dann fange ich jetzt mal an. Ein Aufsatz über so einen alten Zauberer, der irgendwelche Sachen erfunden hat." },
      { type: "text", text: "Ich starrte mein weißes Blatt an. Dann starrte ich meine Federtasche an. Meine Stifte lagen total durcheinander. Blau war neben Rot und Rot war neben Schwarz, Schwarz war neben Gelb. Das geht nicht. Ich sortierte sie nach dem Regenbogen." },
      { type: "text", text: "Okay, jetzt der Aufsatz. Aber vielleicht sollte ich gucken, ob alle Stifte angespitzt sind. Also setzte ich mich ans Anspitzen. Dann machte ich mein Radiergummi sauber und testete alle meine Filzstifte. Ich tauschte die Tintenpatronen in meinem Füller und stellte sicher, dass mein Tintenkiller noch funktionierte. So, jetzt war meine Federtasche bereit zur Benutzung. Moment, ich musste noch den Anspitzer leeren." },
      { type: "sceneBreak" },
      { type: "text", text: "Ich stand also auf, ging in die Küche und sah Krümel, wie er sich auf dem Boden wälzte." },
      { type: "text", text: "\"Na, was hast du denn?\", fragte ich ihn und er miaute. \"Soll ich dich bürsten, Krümel? Du verlierst ja ganz viele Haare!\"" },
      { type: "text", text: "\"Miau!\", machte Krümel und ich verstand es als \"Ja\"." },
      { type: "text", text: "Ich holte Krümels Bürste und legte los. Er schnurrte die gesamte Zeit. Als ich fertig war, glänzte Krümels Fell." },
      { type: "text", text: "Ich stand also auf, um meinem eigentlichen Ziel nachzugehen: den Anspitzer entleeren, da erblickte ich eine traurig guckende Topfpflanze." },
      { type: "text", text: "\"Dich hat auch lange niemand mehr gegossen, nicht wahr, Pflänzchen?\" Ich holte also die Gießkanne, füllte sie mit Wasser und goss die arme Pflanze." },
      { type: "text", text: "Bei dem Anblick des Wassers wurde ich auch ganz durstig, also leerte ich nun wirklich den Anspitzer und schenkte mir und Finn jeweils ein Glas Wasser ein." },
      { type: "text", text: "\"Danke\", sagte Finn und trank alles in einem Schluck." },
      { type: "text", text: "\"Bitte\", sagte ich und setzte mich wieder an mein leeres Blatt. Das leere Blatt. Das weiße Blatt. Das Blatt, wo nichts draufstand. Das Blatt, auf das ich den Aufsatz schreiben musste." },
      { type: "text", text: "\"Finn, hast du Hunger?\", fragte ich und aus Finns Mund kam das \"Ja\" geschossen, noch bevor ich meinen Satz zu Ende gesprochen hatte." },
      { type: "text", text: "\"Perfekt, hast du Lust auf Eierkuchen?\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Als meine Mama die Küche betrat, blieb sie ganz verdutzt stehen. \"Was macht ihr beiden denn da?\" Sie beäugte die dreckige Schüssel, den Schneebesen und die Teigspritzer, die sich über die Arbeitsplatte zogen. Dann fiel ihr Blick auf unsere leicht verbrannten Eierkuchen." },
      { type: "text", text: "\"Ach, Kinder …\", sie schlug sich die Hand auf die Stirn. \"Hattet ihr nicht einen Aufsatz zu schreiben?\"" },
      { type: "text", text: "Finn und ich senkten unsere Köpfe." },
      { type: "text", text: "\"Habt ihr Schwierigkeiten damit?\", fragte Mama besorgt." },
      { type: "text", text: "\"Ja, schon …\", sagte ich." },
      { type: "text", text: "\"Ich wollte die ganze Zeit nur meinen Kopf auf den Tisch hauen\", gab Finn zu. \"Ich weiß nicht, warum das so schwer ist.\"" },
      { type: "text", text: "\"Es ist so ein langweiliger Aufsatz über so einen ganz, ganz alten Zauberer. Es ist so nervig. Ich habe das Gefühl, alles in mir drin wehrt sich dagegen, diesen blöden Text zu schreiben.\" Ich verschränkte meine Arme." },
      { type: "text", text: "\"Wie fühlt sich das denn an, Schatz?\"" },
      { type: "text", text: "\"Alles spannt sich an, meine Finger kribbeln, alles fängt an zu jucken, es ist unerträglich. Ich habe das Gefühl, das nicht aushalten zu können. Ich könnte dann Wände einreißen, so schlimm ist das.\"" },
      { type: "text", text: "\"Wie machen das denn andere Kinder?\", fragte Finn verzweifelt. \"Es fühlt sich unmöglich an.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Mama nickte verständnisvoll: \"Ja, das kann sich sehr wohl unmöglich anfühlen. Manchmal muss man Dinge machen, auf die man gar keine Lust hat, und das ist nicht leicht, vor allem für Kinder mit ADHS.\"" },
      { type: "text", text: "\"Ja, Frau Tintenklecks hatte es uns vorgestern erklärt. Sie meinte, wenn wir etwas ganz toll finden, dann können wir uns drauf konzentrieren, aber wenn wir es doof finden, dann geht das ganz schlecht\", erzählte ich." },
      { type: "text", text: "\"Da hat Frau Tintenklecks recht. Langeweile ist ein ganz unangenehmes Gefühl für Gehirne mit ADHS. Euch fehlt dann oft der Antrieb, die Motivation etwas zu starten. Bei Kindern ohne ADHS kann der Antrieb trotz Langeweile kommen, wenn sie zum Beispiel daran denken, dass sie für ihren Aufsatz eine gute Note bekommen könnten, oder dass sie sich besser fühlen werden, wenn der Aufsatz fertig ist. Bei ADHS ist das anders, da muss man etwas mehr nachhelfen.\"" },
      { type: "text", text: "\"Warum ist das so?\", fragte ich." },
      { type: "text", text: "\"Mit ADHS zählt das Gefühl im Hier und Jetzt oft viel mehr, als was in der Zukunft ist. Ohne ADHS ist das nicht so stark der Fall. Ohne ADHS sagt man sich: Ja, das ist langweilig, aber je früher ich anfange, desto eher habe ich es hinter mir, ich halte die Langeweile für eine Weile aus. Mit ADHS sieht es aber eher so aus: Diese Aufgabe fühlt sich ganz schlimm an und wird wahrscheinlich unendlich lange dauern. Ich kann das nicht aushalten.\"" },
      { type: "text", text: "\"Genau so fühlt sich das an!\", stimmte ich zu. \"Was können wir tun?\"" },
      { type: "text", text: "\"Naja, der Aufsatz klingt echt nicht so spannend\", sagte meine Mama. \"Aber was ist, wenn wir ihn für uns spannender machen?\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Zuallererst holte Mama ein Stück Papier. \"Wir machen jetzt gemeinsam einen Plan\", sagte sie. \"Und wenn wir den Plan gemacht haben, dann gibt es richtige Eierkuchen für euch.\"" },
      { type: "text", text: "Auch wenn es schwierig war, haben wir gemeinsam einen Plan erstellt. Eine Liste, die wir abhaken konnten. Zuerst sollten wir den Text über den Zauberer lesen. Der erste Haken. Dann sollten wir ein paar Stichpunkte aufschreiben. Der zweite Haken. Als drittes die Stichpunkte ordnen, als viertes die Einleitung schreiben, und so weiter, bis der Aufsatz fertig war. Jeder Arbeitspunkt sollte klein und übersichtlich sein. Und nach jedem Haken sollte es eine Belohnung geben." },
      { type: "text", text: "Als der Plan fertig war, schwenkte sie ein Mal ihren Zauberstab und unsere eher ungeglückten Eierkuchen verwandelten sich in goldbraune, mit Sirup übergossene Leckerbissen." },
      { type: "text", text: "\"Kleine Schritte sind besser als keine Schritte\", hatte Mama beim Essen gesagt und als wir fertig waren, ging es für Finn und mich wieder an die Arbeit." },
      { type: "text", text: "Mann, war das eine Qual am Anfang. Ich hatte das Gefühl, jeden Satz fünf Mal lesen zu müssen, bevor mein Gehirn verstand, was da stand. Aber als ich den ersten Haken gesetzt hatte und Mama mir dafür einen süßen Katzensticker gab, konnte ich es kaum erwarten, den nächsten Haken zu setzen." },
      { type: "text", text: "Als Finn und ich mit dem Schreiben anfingen, war meine Aufmerksamkeit aber wieder komplett weg. Ich merkte das, weil Finn mich anstupste und sagte: \"Anabella, ich glaube, du träumst wieder.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "\"Wenn ihr müde seid, dann wäre es doch gut, wenn ihr kurz eine Pause macht\", sagte Mama. \"Die Pause sollte am besten das Gegenteil davon sein, was ihr gerade getan habt. Das heißt, wenn ihr gerade gerannt wärt, dann solltet ihr euch in eurer Pause hinsetzen. Aber wenn ihr die ganze Zeit gesessen habt und euren Kopf angestrengt habt, dann solltet ihr am besten fünf Minuten rausgehen und euch bewegen.\"" },
      { type: "text", text: "\"Dürfen wir Krümel mitnehmen?\", fragte ich aufgeregt." },
      { type: "text", text: "\"Na klar, aber verliert ihn nicht aus den Augen.\"" },
      { type: "text", text: "Krümel zeigte uns ein paar seiner Flugtricks und Finn und ich nahmen unsere Besen und machten es ihm nach. Nach fünf Minuten waren wir sogar ein bisschen außer Atem." },
      { type: "text", text: "\"Bereit weiterzumachen?\", fragte Mama als wir wieder im Haus waren. \"Dieses Mal habe ich noch eine Herausforderung für euch. Ich stelle euch einen Timer für 20 Minuten. Wer von euch es schafft, die ganzen zwanzig Minuten lang zu schreiben, darf sich eine Belohnung aussuchen. Alles klar?\"" },
      { type: "text", text: "\"Ich bin bereit!\", rief ich." },
      { type: "text", text: "\"Ich auch!\", stimmte Finn zu." },
      { type: "text", text: "Ich gebe es zu, es war nicht einfach. Aber ich wollte heute unbedingt gewinnen, nachdem Finn mich gestern beim Aufräumen geschlagen hatte. Also habe ich geschrieben und geschrieben, und weil der Plan so übersichtlich war, habe ich auch nicht lange rätseln müssen, was ich denn machen musste, sondern einfach den nächsten Punkt abgehakt." },
      { type: "text", text: "Finn gab sich aber auch nicht leicht zu schlagen. Er schrieb und schrieb, aber ich sah, wie er immer unruhiger wurde und irgendwann den Stift doch noch fallen ließ." },
      { type: "text", text: "Ja! Nur noch drei Minuten! Ich schrieb ganz schnell, als würde die Zeit schneller vergehen, wenn ich schneller schrieb, und als die zwanzig Minuten vorbei waren, siehe da, da war mein Aufsatz sogar fast fertig." },
      { type: "text", text: "\"Super, Anabella!\", sagte Mama. \"Dann such dir aus, was du gerne machen möchtest.\"" },
      { type: "text", text: "\"Nein, Mama, warte, ich bin doch gleich fertig!\", sagte ich noch und schrieb schnell weiter. Ich merkte gar nicht, wie noch weitere zehn Minuten vergingen und auch Finn die Motivation packte, ein wenig weiterzuschreiben. Geschafft!" },
      { type: "text", text: "\"Fertig!\", rief ich. \"Mama, ich hab den Aufsatz fertig geschrieben!\"" },
      { type: "text", text: "Auch Finn schrieb noch ein paar Minuten und beendete den Aufsatz ebenfalls. Ich war so froh darüber, dass ich das Gefühl hatte, gar keine Belohnung mehr zu brauchen. Trotzdem entschied ich, dass wir mit Mama verstecken spielen würden und so wurde der Nachmittag doch noch ein glücklicher." },
    ],
  },
  {
    id: "freitag",
    weekday: "Freitag",
    title: "Der Tag, an dem ich einen Sturm heraufbeschwor",
    blocks: [
      { type: "text", text: "Ich hatte schlecht geschlafen. Die ganze Nacht habe ich mich gedreht und gewendet und ich fühlte mich am Morgen alles andere als ausgeruht. Die Matheaufgabe meines Weckers machte mich nur sauer, sodass ich zum Ausschalten zu Mama und Papa ins Zimmer gelaufen war und ihnen das piepende Ding in die Hand gedrückt hatte." },
      { type: "text", text: "\"Mein Schatz, ist alles okay?\", fragte mich Mama." },
      { type: "text", text: "\"Ja\", antwortete ich. Aber nichts war okay. Ich war unausgeschlafen, hatte Kopfschmerzen und wollte jetzt nicht auch noch in die Schule gehen." },
      { type: "text", text: "\"Das klang ja sehr glaubwürdig\", lachte Papa, während er den Wecker ausmachte. \"Erzähl, Schatz, was ist los.\"" },
      { type: "text", text: "\"Nichts ist los. Könnt ihr mich nicht einfach in Ruhe lassen!\", schnappte ich." },
      { type: "text", text: "\"Hey, Anabella, wir sind doch auch gerade erst aufgewacht, hab etwas Geduld mit uns. Warum bist du denn so schlecht gelaunt?\"" },
      { type: "text", text: "\"Ich hab keine Sekunde geschlafen\", sagte ich und verschränkte die Arme." },
      { type: "text", text: "\"Ach Mensch, das ist ja doof\", sagte Mama. \"Hast du gestern Abend denn noch was gemacht, nachdem wir Gute Nacht gesagt haben?\"" },
      { type: "text", text: "\"Nein, hab ich gar nicht\", sagte ich. Aber das war gelogen und ich sah meiner Mama an, dass sie das wusste. \"Na gut, ich hab noch das Videospiel gespielt, das mir Finn gezeigt hat.\"" },
      { type: "text", text: "\"Aber Anabellchen, du weißt doch, dass Bildschirme vor dem Schlafengehen ganz schlecht für dich sind …\"" },
      { type: "text", text: "\"Ja, ja, aber das Spiel war so spannend!\"" },
      { type: "text", text: "\"Nur musst du jetzt deswegen müde in die Schule gehen\", sagte Papa und irgendwie machte mich das sauer. Die verstanden mich gar nicht." },
      { type: "text", text: "\"Sollten wir die Konsole nächste Woche lieber wegpacken, damit das nicht nochmal passiert?\", fragte Mama." },
      { type: "text", text: "\"Wie bitte, ihr wollt meine Konsole wegnehmen?\"" },
      { type: "text", text: "\"Nur unter der Woche, Anabella, damit du deinen Schlaf nicht kaputt machst. Am Wochenende kannst du dann wieder spielen.\"" },
      { type: "text", text: "Ich merkte, wie ich rot im Gesicht wurde. \"Ihr seid so doof!\", rief ich und stampfte aus dem Zimmer." },
      { type: "text", text: "Als ich mich fertig machte, um zur Schule zu fliegen, kamen Mama und Papa nochmal zu mir." },
      { type: "text", text: "\"Anabella, wir haben dich lieb und verstehen, dass du heute keine gute Laune hast, aber du kannst uns trotzdem nicht einfach so beleidigen und laut werden.\", sagte Papa, aber ich wollte das alles nicht hören. \"Okay\", zischte ich und ging an ihnen vorbei, schnappte meinen Besen und flog los." },
      { type: "sceneBreak" },
      { type: "text", text: "In der Schule war es schwerer als sonst aufzupassen, auch wenn ich mich durch meinen Flug dahin ein bisschen abgeregt hatte. Finn saß neben mir und klickte hin und wieder seinen Kugelschreiber und mit jedem Klick merkte ich, wie meine Anspannung größer wurde." },
      { type: "text", text: "\"Finn, kannst du das bitte sein lassen?\", sagte ich und Finn packte den Stift weg." },
      { type: "text", text: "Trotzdem trommelte er noch mit seinen Fingern auf seiner Federtasche rum. Normalerweise störte mich das doch gar nicht so sehr, warum machte es mich heute dann so wütend?" },
      { type: "text", text: "\"Finn, bitte!\", sagte ich nochmal." },
      { type: "text", text: "\"Anabella, was ist denn heute los mit dir? Du weißt doch, dass das wegen ADHS ist, dass ich mich so viel bewege, warum bist du gerade so böse?\"" },
      { type: "text", text: "\"Weil das alles deine Schuld ist mit dem doofen Videospiel!\", sagte ich." },
      { type: "text", text: "\"Also gestern fandest du es noch nicht so doof!\", sagte Finn und ich konnte raushören, dass er auch langsam sauer wurde." },
      { type: "text", text: "\"Doch es ist richtig doof!\"" },
      { type: "text", text: "\"Weißt du was, vielleicht bist auch einfach du doof!\", sagte Finn und drehte sich weg. Für den Rest der Stunde redete er nicht mehr mit mir." },
      { type: "sceneBreak" },
      { type: "text", text: "Ich wusste gar nicht, warum ich das gemacht hatte. Warum hatte ich Finn so angefahren? Natürlich war es nicht seine Schuld, dass ich nachts das Spiel gespielt hatte. Bestimmt mochte er mich jetzt nicht mehr. Ich war so eine schlechte Freundin." },
      { type: "text", text: "Frau Tintenklecks benotete heute die Hausaufgaben von gestern. Ich hatte eine gute Note, Finn hingegen hatte nicht so gut abgeschnitten." },
      { type: "text", text: "\"Das ist so unfair!\", rief er, als er seinen Zettel wiederbekam. \"Ich hab mir so Mühe gegeben!\"" },
      { type: "text", text: "Jetzt fühlte ich mich noch schlechter dafür, dass ich vorhin so sauer wurde." },
      { type: "text", text: "Finn knüllte seine Hausaufgabe zusammen und warf sie nach hinten." },
      { type: "text", text: "\"Du, Finn\", sagte ich vorsichtig. \"Ich finde du kannst trotzdem stolz auf dich sein. Mama sagt immer, die Arbeit, die wir gemacht haben, zählt, nicht die Note.\"" },
      { type: "text", text: "\"Anabella, du hast doch gar keine Ahnung! Du hast doch eine gute Note bekommen. Und überhaupt, warum redest du jetzt plötzlich mit mir?\" Er klatschte einmal in die Hand." },
      { type: "text", text: "Stimmt. Finn hasste mich. Ich fühlte so ein Stechen im Magen. Und einen dicken Kloß im Hals. War ich wirklich so schlimm?" },
      { type: "text", text: "Ich fühlte mich schrecklich. Ungeliebt, ungewollt, wertlos." },
      { type: "text", text: "Plötzlich spürte ich, wie etwas Nasses auf mich tropfte. Ich schaute nach oben und, platsch, ein weiterer Tropfen. Über mir hatte sich eine klitzekleine graue Wolke gebildet. Sowas hatte ich noch nie gesehen!" },
      { type: "text", text: "\"Anabella hat eine Wolke auf dem Kopf\", hörte ich meine Klassenkameraden tuscheln. \"Guck mal, die wird immer größer.\"" },
      { type: "text", text: "Tatsächlich! Je verzweifelter ich wurde, desto größer wurde die Wolke." },
      { type: "text", text: "Auch Finn drehte sich wieder zu mir. Ich wollte, dass alle aufhörten zu gucken!" },
      { type: "text", text: "Ich stand auf und rannte aus dem Klassenzimmer und merkte wie einige Schüler aufstanden, um mir hinterherzurennen. Auch Frau Tintenklecks und Finn kamen nach draußen." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Geht weg!\", rief ich. Draußen wurde diese Wolke nur noch mächtiger. Ich war schon komplett durchnässt vom ganzen Regen." },
      { type: "text", text: "\"Geht weg, geht weg!\", versuchte ich nochmal, aber bis auf die Wolke bewegte sich niemand." },
      { type: "text", text: "\"Es braut sich ein Sturm zusammen!\", rief Finn." },
      { type: "text", text: "Ich schaute nach oben und er hatte recht. Die Wolke war hoch in die Luft geflogen und regnete nun nicht nur auf mich, sondern auf alle meine Klassenkameraden und Frau Tintenklecks nieder. Donner grollte. Und dann fiel auch schon der erste Blitz." },
      { type: "text", text: "\"Anabella, du musst dich beruhigen!\"" },
      { type: "text", text: "\"Ich weiß nicht, wie!\", rief ich zurück. Der Wind wehte durch meine Haare und sauste in meinen Ohren. \"Es fühlt sich alles so schlimm an. Ich möchte mich beruhigen, ich kann es nur nicht. Geht doch endlich weg. Ihr werdet alle nass!\"" },
      { type: "text", text: "Die grauen Wolken hatten alles verdunkelt, der Regen fiel in Strömen, der Donner wurde lauter." },
      { type: "text", text: "Frau Tintenklecks schaute noch einmal zu mir, dann hoch, überlegte kurz und nickte. \"Vielleicht lassen wir Anabella mal kurz allein.\"" },
      { type: "text", text: "Allein. Allein. Ich fühlte mich so oft allein." },
      { type: "text", text: "Sie streckte ihre Arme aus und deutete den Kindern wieder in das Klassenzimmer zu gehen." },
      { type: "text", text: "\"Ich bleibe hier\", sagte Finn." },
      { type: "text", text: "\"Wieso?\", fragte ich wütend. \"Du willst doch eh nicht mein Freund sein.\"" },
      { type: "text", text: "Finn schüttelte nur den Kopf." },
      { type: "text", text: "Eine Weile standen wir beide nur da. Ich schaute die ganze Zeit auf den Boden. Bis ich irgendwann merkte, dass es über mir nur noch tröpfelte." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Guck mal, schon ist der Sturm fast weg\", sagte Finn." },
      { type: "text", text: "Er war klatschnass und kam mit einem leichten Lächeln auf mich zu." },
      { type: "text", text: "\"Natürlich möchte ich noch dein Freund sein, Anabella. Das wird sich nicht ändern, nur weil du mal kurz gemein warst. Ich weiß ein bisschen, wie du dich fühlst. An meiner alten Schule habe ich auch einen Sturm heraufbeschworen.\"" },
      { type: "text", text: "\"Das hast du?\", fragte ich überrascht." },
      { type: "text", text: "\"Ja, habe ich. Mehrmals sogar! Danach war ich für eine Weile bei einer Psychotherapeutin. Sie hat mir geholfen, damit die Stürme erst nicht mehr so heftig wurden und danach gar nicht mehr passiert sind.\"" },
      { type: "text", text: "\"Haben die Stürme dann auch was mit ADHS zu tun?\"" },
      { type: "text", text: "Finn nickte. \"Die Therapeutin hat mir erklärt, dass meine Gefühle mich manchmal überwältigen können. Mehr als bei anderen Kindern.\"" },
      { type: "text", text: "\"Ich hasse es, ADHS zu haben\", murmelte ich." },
      { type: "text", text: "\"Ich weiß, ich auch manchmal. Aber auch wenn es nicht ganz leicht ist, man kann lernen mit den Gefühlen klarzukommen, das habe ich auch geschafft. Heute Morgen war ich verletzt von dem, was du gesagt hast, und dann war ich ganz traurig und wütend wegen meiner Note und ich hätte auch gerne einen Tornado losgeschickt. Vielleicht war ich sogar ganz kurz davor, aber ich habe mich daran erinnert, was ich in der Therapie gelernt habe.\"" },
      { type: "text", text: "Ich merkte, wie der Regen aufgehört hatte und die Wolke langsam wieder verschwand." },
      { type: "text", text: "\"Was hast du denn gelernt?\", fragte ich." },
      { type: "text", text: "\"Dass ich manchmal was Schlimmes denke, und dann stimmt das oft gar nicht. Als du gesagt hast, dass ich schuld an allem bin, habe ich zuerst gedacht: Sie mag mich nicht mehr. Deswegen war ich auch so sauer. Dann hab ich mir aber gesagt: Vielleicht hat sie nur einen schlechten Start in den Tag gehabt und es hat gar nichts mit mir zu tun.\"" },
      { type: "text", text: "\"Oh ja, das hatte ich\", sagte ich. \"Aber wie ich mit dir geredet habe, war trotzdem nicht nett, und das tut mir wirklich leid.\"" },
      { type: "text", text: "\"Danach war ich unglücklich wegen der Note. Da wollte ich gerne ausrasten. Aber was ich gelernt habe, war: Einmal in die Hand klatschen heißt Stop! Also habe ich das gemacht. Ich hab geklatscht, bevor ich wirklich ausgerastet wäre. Dann konnte ich nochmal kurz nachdenken.\"" },
      { type: "text", text: "\"Und worüber hast du dann nachgedacht?\"" },
      { type: "text", text: "\"Mehrere Sachen\", sagte Finn. \"Erstmal habe ich darüber nachgedacht, was du gesagt hast. Dass die Arbeit mehr zählt als die Note, und ich denke, du hast recht. Ich habe aber auch gedacht: Ich finde meine Note trotzdem ungerecht. Meine Therapeutin hat mir dann beigebracht, wie ich richtig atmen kann, um mich zu beruhigen. Ich darf es einfach ungerecht finden. Ich muss deswegen aber nicht gleich einen Sturm heraufbeschwören.\"" },
      { type: "text", text: "\"Vielleicht sollte ich dann auch Therapie machen\", sagte ich und schaute auf meine und Finns nasse Kleidung." },
      { type: "text", text: "\"Vielleicht\", sagte Finn. \"Du kannst ja mit deinen Eltern darüber reden.\"" },
      { type: "text", text: "\"Ach Mann, zu meinen Eltern war ich auch fies heute Morgen …\"" },
      { type: "text", text: "Finn lächelte mich an. \"Entschuldige dich einfach. Sie lieben dich trotzdem!\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Nach der Schule landete ich noch kurz auf einem Feld und pflückte ein paar Blumen, bevor ich nach Hause flog. Ich stellte sie in eine Vase und schrieb eine Entschuldigungskarte." },
      { type: "text", text: "Als meine Eltern nach Hause kamen, umarmte ich sie ganz fest und ich konnte es mir nicht verkneifen, in Tränen auszubrechen." },
      { type: "text", text: "Ich erzählte ihnen alles und sie hörten mir aufmerksam zu und als ich ihnen von meinem Gespräch mit Finn erzählte, erwähnte ich auch die Therapie." },
      { type: "text", text: "Meine Eltern fanden die Idee nicht schlecht, sie hatten neben dem Kinderarzt, zu dem wir immer gingen, sowieso schon überlegt, eine Psychotherapie zu versuchen und schlugen vor, dass ich erstmal einen Probetermin machen könnte." },
      { type: "text", text: "\"Danke, dass ihr versucht mich zu verstehen\", sagte ich." },
      { type: "text", text: "\"Natürlich, Anabella, wir lieben dich\", sagte Papa." },
      { type: "text", text: "\"So sehr, mein Schatz\", fügte Mama hinzu." },
      { type: "text", text: "\"Ich euch auch\", sagte ich." },
      { type: "text", text: "Am Abend merkte ich dann, wie vollkommene Ruhe eintrat, als ich in meinem Bett lag und Krümel streichelte. Wie ADHS wohl bei Katern aussah, fragte ich mich, und schlief langsam aber tief und fest mit einem schnurrenden Krümel im Arm ein." },
    ],
  },
  {
    id: "samstag",
    weekday: "Samstag",
    title: "Der Tag, an dem ich die Retterin war",
    blocks: [
      { type: "text", text: "Heute weckte mich die Sonne." },
      { type: "text", text: "Es war Samstag, deswegen brauchte ich keinen Mathe-Wecker. Es war schön auszuschlafen, vor allem nach der unruhigen Nacht gestern. Ich freute mich bereits auf den freien Tag. Heute würde ich mit Finn und Krümel in den Park gehen." },
      { type: "text", text: "Also sprang ich auf, zog mich an und lief zu meinen Eltern in die Küche." },
      { type: "text", text: "Mein Papa hatte bereits Frühstück vorbereitet. Leckere, frische Brötchen mit Butter und Käse, Marmelade und Schokoaufstrich. Ich nahm von jeder Sorte ein bisschen was. Zusätzlich gab es Orangensaft." },
      { type: "text", text: "\"Na, freust du dich auf deinen Tag mit Finn?\", fragte meine Mama." },
      { type: "text", text: "\"Ja\", antwortete ich. \"Wir gehen mit Krümel in den Park und nehmen unsere Besen mit. Dann kann uns Krümel wieder ein paar seiner Flugtricks zeigen. Und vielleicht können wir ihm dieses Mal auch welche zeigen.\"" },
      { type: "text", text: "\"Das klingt ja aufregend\", sagte Mama. \"Dann wünsche ich euch ganz viel Spaß dabei. Aber passt auf Krümel auf! Verliert ihn nicht aus den Augen, alles klar?\"" },
      { type: "text", text: "\"Alles klar\", sagte ich." },
      { type: "text", text: "Und dann ging es auch schon los." },
      { type: "text", text: "Finn wartete dort bereits auf mich." },
      { type: "text", text: "\"Wie geht's dir heute?\", fragte er mich." },
      { type: "text", text: "\"Viel besser!\", sagte ich. \"Versprochen, heute ohne Sturm!\"" },
      { type: "text", text: "Er lachte." },
      { type: "text", text: "\"Ich habe sogar mit meinen Eltern gesprochen, wegen der Therapie, und sie haben gesagt, dass das eine gute Idee ist.\"" },
      { type: "text", text: "\"Cool!\", rief er. Dann flogen wir los." },
      { type: "sceneBreak" },
      { type: "text", text: "Krümel allen voraus drehte und rollte sich in der Luft und wir taten es ihm nach." },
      { type: "text", text: "\"Guck mal, Krümel!\", rief ich und machte einen großen Looping. Der Kater miaute, als wolle er sagen: \"Ich kann das viel besser\" und machte gleich zwei." },
      { type: "text", text: "\"Krümel, du Angeber!\", lachte Finn, versuchte sich aber sofort an drei Loopings. Leider wurde ihm danach etwas schwindelig und ich könnte schwören, Krümel lachte ihn ein bisschen aus. Ich wusste gar nicht, dass Kater lachen konnten, aber Krümel war halt was ganz Besonderes." },
      { type: "text", text: "Finn zeigte mir noch einen Trick, bei dem er ganz hoch flog und dann ganz schnell wieder runter, bis er kurz über dem Boden zum Stehen kam. Sofort versuchte ich das auch. Dann flogen wir um die Wette. Wir merkten gar nicht, wie es langsam Nachmittag wurde." },
      { type: "text", text: "\"Finn, es ist schon spät\", sagte ich, nachdem ich auf meine Uhr schaute." },
      { type: "text", text: "\"Oh, du hast recht\", er grinste mich an. \"Man könnte sagen, die Zeit vergeht wie im Flug.\"" },
      { type: "text", text: "\"Ha-ha\", machte ich kopfschüttelnd. \"Du bist ja lustig.\"" },
      { type: "text", text: "\"Dann lass uns mal schnell nach Hause. Deine Eltern warten bestimmt schon mit dem Mittagessen.\"" },
      { type: "text", text: "Ich nickte und wir schwangen uns auf unsere Besen. Auf dem Weg hatte ich aber ein komisches Gefühl, so, als fehlte etwas." },
      { type: "sceneBreak" },
      { type: "text", text: "Zuhause angekommen, erzählten wir Mama und Papa ganz aufgeregt von unseren Tricks." },
      { type: "text", text: "\"Wow! Das klingt ja super\", sagte Papa. \"Und hatte Krümel auch Spaß?\"" },
      { type: "text", text: "Sofort drehte sich Finn zu mir und meine Augen weiteten sich. Krümel! Wir hatten Krümel vergessen!" },
      { type: "text", text: "\"Wo ist er denn überhaupt?\", fragte Mama und schaute sich um." },
      { type: "text", text: "Mein Herz pochte. Wie konnte ich ihn nur dort lassen? Mein liebster kleiner Kater …" },
      { type: "text", text: "Mama sah meinen Blick." },
      { type: "text", text: "\"Ihr habt ihn doch nicht im Park vergessen?\", fragte sie erschrocken. Ich konnte nur ganz langsam nicken. Dann zuckte ich aber wie gestochen hoch." },
      { type: "text", text: "\"Wir fliegen sofort zurück\", sagte ich und verschwendete keine weitere Sekunde. \"Wir sind noch nicht lange hier, es ist bestimmt nicht schwer ihn zu finden.\"" },
      { type: "text", text: "Finn und meine Eltern kamen mit. Wir alle nahmen unsere Besen und flogen wie der Wind zurück in den Park." },
      { type: "sceneBreak" },
      { type: "text", text: "Ich schaute hinter jedem Baum, in jedem Gebüsch, überflog jede Wiese in der Hoffnung, einen Blick des orangenen Katers zu erhaschen." },
      { type: "text", text: "\"Krümel!\", rief ich. \"Krümel!\" Aber es kam nichts zurück, kein Miauen, kein Fauchen, nichts." },
      { type: "text", text: "\"Wo bist du denn …\"" },
      { type: "text", text: "Minuten wurden zu Stunden und Krümel tauchte immer noch nicht auf. Er war wie vom Erdboden verschluckt." },
      { type: "text", text: "Mama und Papa wurden irgendwann müde und flogen nach Hause, Finn und ich aber blieben noch länger." },
      { type: "text", text: "\"Ich vermisse ihn jetzt schon so sehr\", sagte ich zu Finn und er gab mir eine feste Umarmung." },
      { type: "text", text: "\"Wir werden ihn schon finden\", versuchte er mich zu beruhigen." },
      { type: "text", text: "\"Weißt du, meine Therapeutin hat mir noch eine Sache über ADHS beigebracht - und zwar, wenn wir etwas ganz dolle wollen, dann lassen wir nicht locker.\"" },
      { type: "text", text: "\"Ich will unbedingt Krümel finden! Und ich werde nicht lockerlassen!\"" },
      { type: "text", text: "\"Dann schaffen wir das auch\", nickte Finn." },
      { type: "text", text: "Noch eine weitere Stunde suchten wir vergebens, bis wir auch nach Hause flogen. Zeit für neue Ideen." },
      { type: "sceneBreak" },
      { type: "text", text: "\"Hier ist der Plan\", sagte ich und kippte meine Bastelkiste auf dem Boden aus. \"Du nimmst Kleber und Schere und ich nehme mir meine Buntstifte. Ich male Krümel auf Papier und du schneidest ihn aus und klebst ihn auf die Plakate.\"" },
      { type: "text", text: "\"Dann schreiben wir ganz groß: Orangener fliegender Kater gesucht\", fügte Finn hinzu." },
      { type: "text", text: "\"Perfekt. Außerdem: hört auf Krümel und kuschelt gerne.\"" },
      { type: "text", text: "\"Und: kann coole Tricks\"" },
      { type: "text", text: "\"Super\", sagte ich und wir machten uns sofort an die Arbeit. Ich malte einen Krümel nach dem anderen und Finn schnitt die Zeichnungen aus und klebte sie auf die großen roten Pappplakate. Wir haben uns für rot entschieden, damit jeder in der Nachbarschaft sie auch gut sehen konnte." },
      { type: "text", text: "Wieder vergingen Stunden. Zwischendurch kam mein Papa ins Zimmer und brachte uns etwas zu essen. \"Die fleißigen Arbeiter brauchen ja auch ihren Kraftstoff\", hatte er gesagt. Ich hatte gar nicht bemerkt, wie sehr mein Magen gegrummelt hatte, ich war so auf die Plakate konzentriert." },
      { type: "text", text: "Das ist bestimmt das, was Frau Tintenklecks meinte. Manchmal können wir uns nicht so gut konzentrieren und manchmal zu gut. Und jetzt ging es um alles, also war meine Konzentration stärker denn je." },
      { type: "text", text: "Als wir fertig waren, hatten wir zwanzig Plakate." },
      { type: "sceneBreak" },
      { type: "text", text: "Finn und ich hängten sie um die Wette auf. Er hatte zehn und ich hatte zehn Plakate. Wir flogen die gesamte Nachbarschaft ab und die meisten Plakate hängten wir in der Nähe des Parks auf. Finn war fertig, als ich gerade mal fünf Plakate aufgehängt hatte." },
      { type: "text", text: "\"Gewonnen\", er stupste meine Schulter an." },
      { type: "text", text: "\"Ja, ja, du hast doch bestimmt geschummelt\", spaßte ich." },
      { type: "text", text: "\"Hmm… klingt für mich nach einer schlechten Verliererin.\" Er verschränkte die Arme und grinste." },
      { type: "text", text: "\"Lachst du mich etwa aus?\"" },
      { type: "text", text: "\"Nein, das würde ich niemals machen!\"" },
      { type: "text", text: "Ich streckte ihm die Zunge aus. Es war schön, dass wir trotz der Angst um Krümel noch ein bisschen lachen konnten." },
      { type: "text", text: "\"Gib mir noch ein paar\", sagte er dann. \"Ich kann doch sowieso nicht stillsitzen, dann ist das heute mal zu was gut!\"" },
      { type: "text", text: "Ich drückte ihm alle meine Plakate in die Hand. \"Dann häng du den Rest auf. Ich habe in der Zwischenzeit noch eine andere Idee!\"" },
      { type: "text", text: "Ich schwang mich auf den Besen und flog nochmal nach Hause." },
      { type: "sceneBreak" },
      { type: "text", text: "Spielzeug. Decke. Leckerlis. Was noch? Was mag Krümel gerne?" },
      { type: "text", text: "Ich schaute aus dem Fenster und sah, wie es langsam dunkel wurde. Ich machte mir große Sorgen um ihn. Nachts, alleine, das ist bestimmt gruselig. Er wird bestimmt Angst haben." },
      { type: "text", text: "Spielzeug. Decke. Leckerlis. Vielleicht noch ein Kissen? Und mein Kuscheltier?" },
      { type: "text", text: "Aus Holzplatten im Garten hatte ich mit Papa zusammen eine große Kiste gezaubert. Sie war nicht perfekt, aber es musste ja schnell gehen. Vorne hatten wir es aber noch geschafft, eine Art Katzenklappe einzubauen." },
      { type: "text", text: "Als wir fertig waren, war Finn auch schon wieder zuhause." },
      { type: "text", text: "\"Ich möchte nicht, dass Krümel sich einsam fühlt, heute Nacht\", erklärte ich Finn." },
      { type: "text", text: "\"Was hast du vor?\", fragte er." },
      { type: "text", text: "Ich zeigte ihm die Kiste und erzählte ihm, dass ich sie gerne mit Sachen füllen wollte, die Krümel gerne mochte und sie dann anschließend in den Park stellen wollte. Die Kiste sollte ganz gemütlich sein, damit er sich darin wohl fühlen würde und vielleicht die Nacht darin schlafen konnte." },
      { type: "text", text: "Also fingen wir erstmal mit einer weichen Decke an. Ich holte noch zwei Kissen und mein Kuscheltier. \"Krümel braucht das heute mehr als ich.\"" },
      { type: "text", text: "Wir suchten seine Lieblingsspielzeuge und legten noch eine Schüssel mit Futter rein." },
      { type: "text", text: "Zum Schluss zauberte ich noch ein paar Lichter rein, damit Krümel auch was sehen kann. Ich habe die Lichter so verzaubert, dass er sie nur antippen braucht, damit sie ausgehen, damit er auch in Ruhe schlafen kann." },
      { type: "text", text: "So verwandelte sich die Kiste in ein kleines Häuschen." },
      { type: "text", text: "\"Jetzt muss uns nur noch einfallen, wie wir ihn anlocken können.\"" },
      { type: "sceneBreak" },
      { type: "text", text: "Je länger Finn und ich redeten, desto mehr Einfälle hatten wir. Die Ideen sprudelten nur so aus uns heraus. Am Ende haben wir uns aber für einen Duftzaubertrank entschieden, den wir auf die Kiste träufeln wollten." },
      { type: "text", text: "\"Wenn ich Krümel wäre, welchem Duft würde ich folgen?\", fragte ich mich. Ich schloss meine Augen und versuchte mich komplett in meinen Kater hineinzuversetzen. Ich wäre im Park, ich würde sehen, wie die Sonne unterging, und ich würde wahrscheinlich ein unruhiges Gefühl haben. Je dunkler es werden würde, desto mehr Angst hätte ich. Was würde ich am ehesten wollen? Ich würde mein Zuhause vermissen. Ich würde dem Duft von Zuhause folgen. Zuhause und … und ich hätte ja eine Weile nichts gegessen. Zuhause und der Duft von frischem Katzenfutter. Und … und Liebe! Ich würde die Liebe meiner Familie vermissen. Wie machte man denn einen Liebesduft?" },
      { type: "text", text: "Ich öffnete meine Augen wieder und nahm meinen Hexenkessel in die Hand. \"Zuerst sein Katzenfutter!\", sagte ich." },
      { type: "text", text: "Sofort sprang Finn auf und holte es." },
      { type: "text", text: "\"Dann ein Blatt von der Pflanze in der Küche.\"" },
      { type: "text", text: "Auch das holte Finn rasch." },
      { type: "text", text: "\"Eine alte Socke von mir.\"" },
      { type: "text", text: "Die Socke packte Finn ganz weit weg von sich mit Daumen und Zeigefinger und rümpfte die Nase. \"Hier hast du\", sagte er angeekelt und ich rollte die Augen." },
      { type: "text", text: "\"Mein Lieblingsbuch.\"" },
      { type: "text", text: "Er holte die Königin des Feuers und ich riss eine Seite daraus. Finn schaute mich mit großen Augen an." },
      { type: "text", text: "\"Warum hast du das getan?\", fragte er." },
      { type: "text", text: "\"Für Krümel würde ich alles tun\", antwortete ich. \"Ich lese dieses Buch oft mit ihm in meinen Armen, der Duft der Seiten wird ihn an zuhause erinnern.\"" },
      { type: "text", text: "Dann machten wir noch eine Mischung des Spülmittels, der Handseife, des Duschgels und der Zahnpasta, die wir benutzten, rein. Meine Mama fügte ein paar Spritzer ihres Parfüms hinzu und mein Papa tropfte seinen Morgenkaffee in den Kessel." },
      { type: "text", text: "Fast fertig." },
      { type: "sceneBreak" },
      { type: "text", text: "Die Sonne war nun komplett untergegangen und Finn musste leider nach Hause. Er hat mir aber versprochen morgen sofort vorbeizukommen, um zu sehen, was passiert. Ich verabschiedete mich von ihm und bedankte mich für alles." },
      { type: "text", text: "Der Trank blubberte schon vor mir." },
      { type: "text", text: "\"Jetzt nur noch der Liebesduft\", sagte ich. Mama und Papa guckten mich ganz verwirrt an." },
      { type: "text", text: "\"Glaubt mir\", sagte ich ihnen. \"Ohne Liebe wird das nicht funktionieren!\"" },
      { type: "text", text: "\"Okay, aber wie soll das gehen?\", sagte Papa." },
      { type: "text", text: "\"Wir müssen Krümel zeigen, wie sehr wir ihn lieben\", antwortete ich. \"Denkt nach, jeder von uns hat seine Art und Weise, seine Liebe zu zeigen!\"" },
      { type: "text", text: "Ich musste aber selber erst nachdenken. Was machte ich denn mit Krümel, was ihm meine Liebe zeigte? War es das Lesen im Bett? Aber nein, da schlief er ja nur. War es das Bürsten seiner Haare? Nein, das vergaß ich ja sogar manchmal. Ich hatte es! Es war das gemeinsame Fliegen. Ich lief also zu meinem Besen und schnitt eine Borste ab, die ich dann in den Kessel warf." },
      { type: "text", text: "\"Jetzt ihr!\", forderte ich die anderen auf und jeder fügte dem Trank ein bisschen Liebe hinzu." },
      { type: "text", text: "Nur noch ein bisschen umrühren und ein paar Zauber sprechen und der Trank war fertig." },
      { type: "sceneBreak" },
      { type: "text", text: "Der Park sah im Dunkeln ganz anders aus. Viel unheimlicher, als wenn die Sonne schien. Wir stellten das Katzenhäuschen ab und betröpfelten es mit dem Trank. Dann träufelte ich auch etwas davon um die Kiste herum." },
      { type: "text", text: "\"Mehr können wir jetzt nicht mehr machen\", sagte Mama." },
      { type: "text", text: "Mir fielen aber noch tausend weitere Sachen ein, die wir hätten machen können." },
      { type: "text", text: "\"Es ist spät, Anabella. Ich weiß, es ist schwer, aber du solltest versuchen zu schlafen. Du hast heute so hart gearbeitet, du musst deinen Körper ruhen lassen.\"" },
      { type: "text", text: "Sie hatte recht. Ich hatte nicht einmal wahrgenommen, wie müde ich eigentlich war." },
      { type: "sceneBreak" },
      { type: "text", text: "Im Bett gab mir Papa einen Kuss auf die Stirn. \"Ich bin stolz auf dich\", sagte er, aber es fiel mir schwer, das anzunehmen." },
      { type: "text", text: "\"Wieso denn? Ich habe Krümel verloren … blöde ADHS\"" },
      { type: "text", text: "\"Ja, und das sollte am besten nie wieder passieren. Aber du hast heute auch so viel Stärke gezeigt, Schatz. Ich bin mir sicher, dass wir ihn deinetwegen wiederfinden werden und vielleicht hat die ADHS ja auch ein bisschen eine Rolle dabei gespielt.\"" },
      { type: "text", text: "\"Ich weiß ja nicht …\"" },
      { type: "text", text: "\"Du warst einfallsreich, kreativ, du hast all die Energie in die Suche gesteckt, die du hattest und du hast nicht locker gelassen. Und ganz wichtig, du hast auch ganz viel Mitgefühl mit Krümel gezeigt, nur so hast du diesen Trank brauen können. Das sind alles Stärken, Schatz. Ja, du bist hin und wieder abgelenkt, aber das kann in Situationen wie heute zu ganz vielen tollen Ideen führen. Du versinkst manchmal in deiner eigenen Welt, aber heute war das genau richtig, du warst so fokussiert auf dein Ziel, du hast den ganzen Tag daran gearbeitet. Du fühlst oft ganz viel, und heute hast du uns dadurch einen zauberhaften Trank gebraut. Du bist eine wundervolle, starke Hexe, Anabella.\"" },
      { type: "text", text: "\"Das ADHS hat also auch gute Seiten?\"" },
      { type: "text", text: "\"Ja, und heute ist der Beweis dafür gewesen. Auch Finn hat seinen Bewegungsdrang gut ausnutzen können, nicht wahr? Oft sind wir so auf die schlechten Sachen fixiert. Da vergessen wir, was gut an uns ist. Du bist gut. Sehr gut sogar. Und du bist auch mehr als nur ADHS, weißt du. Du bist humorvoll, intelligent, liebevoll, du bist begeisterungsfähig, lebendig, hast große Träume … vergiss das nicht.\"" },
      { type: "text", text: "\"Okay, Papa\", sagte ich. Ich bin mehr als mein ADHS. Das verliere ich manchmal aus den Augen." },
      { type: "text", text: "Es dauerte eine Weile, und ich drehte und wendete mich, aber irgendwann schlief ich dann doch noch ein." },
    ],
  },
  {
    id: "sonntag",
    weekday: "Sonntag",
    title: "Der Tag, an dem ich einfach ich war",
    blocks: [
      { type: "text", text: "Ich war bei Sonnenaufgang bereits auf den Beinen und weckte meine Eltern." },
      { type: "text", text: "\"Wir müssen in den Park. Jetzt!\", bestand ich." },
      { type: "text", text: "Verschlafen zogen sie sich aus dem Bett und wir flogen los." },
      { type: "text", text: "\"Krümel? Krümel?\", rief ich, während ich auf die Box zurannte und den Deckel öffnete. \"Krümel?\" Nichts. Da war nichts. Kein Krümel. Kein orangefarbenes Fell. Kein schnurrender Kater. Die Tränen kamen hochgeschossen." },
      { type: "text", text: "\"Er ist nicht da\", schluchzte ich. \"Er ist nicht da, Krümel ist nicht da.\"" },
      { type: "text", text: "Aber plötzlich: \"Miau.\"" },
      { type: "text", text: "Aus dem Gebüsch nebenan lugte ein orangefarbener Schwanz hervor, dann hörte ich auf einmal einen Wasserstrahl." },
      { type: "text", text: "\"Doch, doch, da ist er\", lachte Mama. \"Er verrichtet nur sein Geschäft im Busch.\"" },
      { type: "text", text: "Meine Tränen verwandelten sich in Freudentränen." },
      { type: "text", text: "Er kam aus dem Gebüsch gekrabbelt und streckte sich, dann miaute er mich an, als ob ich ihn so früh am Morgen gestört hätte. Dieser Kater, wenn er nur wüsste, was für Sorgen ich mir um ihn gemacht hatte. Ich konnte gar nicht aufhören zu weinen. Es hatte geklappt. Wir hatten ihn wirklich gefunden." },
      { type: "text", text: "Er schmiegte sich an meine Beine und ich umarmte ihn ganz fest. \"Ich werde dich nie wieder aus den Augen verlieren. Versprochen.\"" },
      { type: "text", text: "Dann setzten sich Mama und Papa dazu und wir hielten uns fest. Für eine Weile gab es nichts anderes. Mama, Papa, Krümel und ich." },
      { type: "sceneBreak" },
      { type: "text", text: "Zuhause kam Finn vorbei. Ich erzählte ihm die tolle Nachricht, zeigte ihm Krümel, der jetzt schon wieder ein Schläfchen machte. Auch er war glücklich, dass er wieder da war, und streichelte sein weiches Fell." },
      { type: "text", text: "\"Danke für deine Hilfe gestern\", sagte ich. \"Ohne dich hätten wir das nicht geschafft.\"" },
      { type: "text", text: "\"Nicht dafür. Ich helfe gerne, wo ich kann.\"" },
      { type: "text", text: "\"Ich weiß\", sagte ich. \"Danke, wirklich.\"" },
      { type: "text", text: "Er lächelte mich an." },
      { type: "text", text: "\"Papa hat mir gestern erzählt, dass ADHS auch gut sein kann\", sagte ich ihm. \"Und dass wir gestern unsere Stärken genutzt haben.\"" },
      { type: "text", text: "Finn nickte. \"Das glaube ich auch.\"" },
      { type: "text", text: "\"Er hat auch gesagt, dass wir mehr sind als ADHS und dass ich das nicht vergessen soll.\"" },
      { type: "text", text: "\"Das möchte ich auch nicht vergessen\", sagte Finn." },
      { type: "text", text: "Ich war glücklich, ihn als Freund zu haben. Wenn ich uns so ansah, dann waren wir wirklich mehr als unsere ADHS. So viel mehr." },
      { type: "text", text: "\"Weißt du, du bist unglaublich hilfsbereit, du bist sportlich, du bist freundlich …\", fing ich an." },
      { type: "text", text: "\"Ach hör doch auf, ich kann sowas nicht hören!\", lachte Finn." },
      { type: "text", text: "\"Lustig, verständnisvoll, …\", machte ich weiter. \"Ein bisschen nervig-\"" },
      { type: "text", text: "\"Hey!\", machte Finn. \"Wenn einer hier nervig ist, dann bist das du! Aber auch super kreativ und erfinderisch, schlau, ein bisschen verrückt …\"" },
      { type: "text", text: "\"Okay, okay, das reicht\", lachte ich. \"Möchtest du ein Eis essen?\"" },
      { type: "text", text: "\"Liebend gern!\"" },
      { type: "text", text: "Den Rest des Sonntags verbrachten wir ruhig und zufrieden." },
      { type: "text", text: "Wir tankten Energie und machten uns bereit — für eine weitere verhexte Woche." },
    ],
  },
];
